# -*- coding: utf-8 -*-
"""aula1.ipynb

Automatically generated by Colab.

Instalação de bibliotecas
"""

#!pip install kaggle python-dotenv ipython

"""Importar bibliotecas necessárias:"""

import os
import json
import tkinter
import pandas as pd
import matplotlib.pyplot as plt
from kaggle.api.kaggle_api_extended import KaggleApi
from tkinter import Tk, filedialog

kaggle_json_path = os.path.expanduser("~/.kaggle/kaggle.json") 

try:
    with open(kaggle_json_path, 'r') as file:
        dados = json.load(file)
except FileNotFoundError:
    print("Arquivo não encontrado!")
except json.JSONDecodeError:
    print("JSON inválido!")

dados

# PASSO 3: Configurar variáveis de ambiente
os.environ['KAGGLE_USERNAME'] = dados['username']
os.environ['KAGGLE_KEY'] = dados['key']

try:
    api = KaggleApi()
    api.authenticate()
    print("Autenticação bem-sucedida !")

    # Teste
    print("\nSeus datasets:")
    print(api.dataset_list())

except Exception as e:
    print(f"❌ Erro: {e}")

dataset_name = "advaypatil/youtube-statistics"
download_path="/content/data"
api.dataset_download_files(dataset_name, path=download_path, unzip=True)

file_name="videos-stats.csv"

file_path = f"{download_path}/{file_name}"

if os.path.exists(file_path):
    print(f"Arquivo encontrado: {file_path}")


    df = pd.read_csv(file_path)

    pd.set_option('display.max_columns', None) 
    pd.set_option('display.width', None) 
    
    # Exibir informações sobre o DataFrame
    df.info()  # Exibe informações gerais sobre o DataFrame
    print("\nPrimeiras 5 linhas do DataFrame:")
    print(df.head()) 
    print("\nDescrição estatística do DataFrame:")
    print(df.describe())
else:
    print(f"❌ Arquivo não encontrado: {file_path}")
    

def calculate_null_zero_percentage(df):
    total_values = df.size
    null_values = df.isnull().sum().sum()
    zero_values = (df == 0).sum().sum()
    
    null_percentage = (null_values / total_values) * 100
    zero_percentage = (zero_values / total_values) * 100
    
    return null_percentage, zero_percentage

null_percentage, zero_percentage = calculate_null_zero_percentage(df)

print(f"Percentual de valores nulos: {null_percentage:.2f}%")
print(f"Percentual de valores zeros: {zero_percentage:.2f}%")